# Generated by Django 4.2.14 on 2024-11-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='is_recommendet',
            field=models.BooleanField(default=False),
        ),
    ]
