# Generated by Django 4.2.14 on 2024-11-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
        ('users', '0002_recommendation_is_recommendet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='article',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='is_recommendet',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='less_recommended',
            field=models.ManyToManyField(related_name='articles_less_recommended', to='articles.article'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='more_recommended',
            field=models.ManyToManyField(related_name='articles_more_recommended', to='articles.article'),
        ),
    ]
