# Generated by Django 4.2.14 on 2024-12-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
        ('users', '0004_alter_recommendation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='less_recommended',
            field=models.ManyToManyField(blank=True, related_name='articles_less_recommended', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='more_recommended',
            field=models.ManyToManyField(blank=True, related_name='articles_more_recommended', to='articles.article'),
        ),
    ]
