# Generated by Django 4.2.14 on 2024-11-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_first_name_en_customuser_first_name_ru_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="first_name_en",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="first_name_ru",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="first_name_uz",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_name_en",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_name_ru",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_name_uz",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="middle_name_en",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="middle_name_ru",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="middle_name_uz",
        ),
    ]
