# Generated by Django 4.2.14 on 2024-11-21 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="topic",
            new_name="topics",
        ),
    ]
