# Generated by Django 4.2.14 on 2024-12-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("publish", "Publish"),
                    ("trash", "Trash"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
