# Generated by Django 4.2.14 on 2024-12-03 15:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_article_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="topic",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
