# Generated by Django 4.2.14 on 2024-11-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_remove_article_topics_article_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="topics",
            field=models.ManyToManyField(
                blank=True, related_name="topics", to="articles.topic"
            ),
        ),
    ]
