# Generated by Django 4.2.14 on 2024-11-22 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_alter_article_thumbnail_alter_article_topics"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "Article", "verbose_name_plural": "Articles"},
        ),
    ]
