# Generated by Django 4.2.14 on 2024-11-22 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_alter_article_options_alter_article_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "Article", "verbose_name_plural": "Articles"},
        ),
    ]
