# Generated by Django 4.2.14 on 2024-11-22 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0008_alter_article_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
    ]
