# Generated by Django 4.2.14 on 2024-11-22 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0009_alter_article_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={
                "ordering": ["name"],
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
            },
        ),
        migrations.AlterModelTable(
            name="topic",
            table="topic",
        ),
    ]
