GET http://127.0.0.1:8000/users/me/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMxMzg0OTc0LCJpYXQiOjE3MzEzODEzNzQsImp0aSI6IjZiNzNkYTBjNzU4YTQ2MDhhMGQ3NGExMDE4M2VmZjQxIiwidXNlcl9pZCI6MX0.z6YdIw1yYzTIlIvdUkiFV-2XOiKwnFaEjFiJ239gCWA
